"use strict";(self.webpackChunkvp=self.webpackChunkvp||[]).push([[64913],{9423:(e,a,t)=>{t.r(a),t.d(a,{comp:()=>l,data:()=>d});var r=t(60362);const s=t.p+"assets/img/cc26xr1_revision.6de88388.png",n=t.p+"assets/img/good-vs-bad-usb-cable.1cf10550.jpg",o={class:"table-of-contents"},i={},l=(0,t(60654).A)(i,[["render",function(e,a){const t=(0,r.g2)("router-link"),i=(0,r.g2)("RouteLink");return(0,r.uX)(),(0,r.CE)("div",null,[a[58]||(a[58]=(0,r.Lk)("h1",{id:"zigbee2mqtt-fails-to-start-crashes-runtime",tabindex:"-1"},[(0,r.Lk)("a",{class:"header-anchor",href:"#zigbee2mqtt-fails-to-start-crashes-runtime"},[(0,r.Lk)("span",null,"Zigbee2MQTT fails to start/crashes runtime")])],-1)),a[59]||(a[59]=(0,r.Lk)("p",null,"Most of the time this is caused by Zigbee2MQTT not being able to communicate with your Zigbee adapter.",-1)),(0,r.Lk)("nav",o,[(0,r.Lk)("ul",null,[(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#error-usb-adapter-discovery-error-no-valid-usb-adapter-found-specify-valid-adapter-and-port-in-your-configuration"},{default:(0,r.k6)(()=>[...a[0]||(a[0]=[(0,r.eW)("Error: USB adapter discovery error (No valid USB adapter found). Specify valid 'adapter' and 'port' in your configuration.",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#error-srsp-sys-ping-after-6000ms-for-zstack-or-host-fatal-error-for-emberznet"},{default:(0,r.k6)(()=>[...a[1]||(a[1]=[(0,r.eW)("Error: SRSP - SYS - ping after 6000ms for zStack or HOST_FATAL_ERROR for EmberZNet",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#verify-that-you-put-the-correct-port-in-configuration-yaml"},{default:(0,r.k6)(()=>[...a[2]||(a[2]=[(0,r.eW)("Verify that you put the correct port in configuration.yaml",-1)])]),_:1}),(0,r.Lk)("ul",null,[(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#which-port-should-i-use-for-texas-instruments-launchxl-cc26x2r1-cc1352p-2-dev-ttyacm0-or-dev-ttyacm1"},{default:(0,r.k6)(()=>[...a[3]||(a[3]=[(0,r.eW)("Which port should I use for Texas Instruments LAUNCHXL-CC26X2R1/CC1352P-2, /dev/ttyACM0 or /dev/ttyACM1?",-1)])]),_:1})])])]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#verify-that-the-user-you-run-zigbee2mqtt-as-has-write-access-to-the-port"},{default:(0,r.k6)(()=>[...a[4]||(a[4]=[(0,r.eW)("Verify that the user you run Zigbee2MQTT as has write access to the port",-1)])]),_:1}),(0,r.Lk)("ul",null,[(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#method-1-give-your-user-permissions-on-every-reboot"},{default:(0,r.k6)(()=>[...a[5]||(a[5]=[(0,r.eW)("Method 1: Give your user permissions on every reboot.",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#method-2-add-your-user-to-specific-groups"},{default:(0,r.k6)(()=>[...a[6]||(a[6]=[(0,r.eW)("Method 2: Add your user to specific groups",-1)])]),_:1})])])]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#error-coordinator-failed-to-start-probably-the-panid-is-already-in-use-try-a-different-panid-or-channel"},{default:(0,r.k6)(()=>[...a[7]||(a[7]=[(0,r.eW)("Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#error-resource-temporarily-unavailable-cannot-lock-port"},{default:(0,r.k6)(()=>[...a[8]||(a[8]=[(0,r.eW)("Error: Resource temporarily unavailable Cannot lock port",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#raspberry-pi-users"},{default:(0,r.k6)(()=>[...a[9]||(a[9]=[(0,r.eW)("Raspberry Pi users",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#raspberry-pi-os"},{default:(0,r.k6)(()=>[...a[10]||(a[10]=[(0,r.eW)("Raspberry Pi OS",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#use-a-good-power-supply"},{default:(0,r.k6)(()=>[...a[11]||(a[11]=[(0,r.eW)("Use a good power supply",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#make-sure-the-extension-cable-works"},{default:(0,r.k6)(()=>[...a[12]||(a[12]=[(0,r.eW)("Make sure the extension cable works",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#for-openhab-users-disable-zwave-binding"},{default:(0,r.k6)(()=>[...a[13]||(a[13]=[(0,r.eW)("For Openhab users: disable zwave binding",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#in-case-of-a-cc2530-or-cc2531-adapter-verify-that-don-t-have-a-cc2540"},{default:(0,r.k6)(()=>[...a[14]||(a[14]=[(0,r.eW)("In case of a CC2530 or CC2531 adapter, verify that don't have a CC2540",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#modemmanager-is-installed"},{default:(0,r.k6)(()=>[...a[15]||(a[15]=[(0,r.eW)("ModemManager is installed",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#make-sure-your-computer-has-enough-resources-available"},{default:(0,r.k6)(()=>[...a[16]||(a[16]=[(0,r.eW)("Make sure your computer has enough resources available",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#hciuart-is-running"},{default:(0,r.k6)(()=>[...a[17]||(a[17]=[(0,r.eW)("hciuart is running",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#texas-instruments-launchxl-cc1352p-2-cc26x2r1-only-press-the-reset-button-on-the-device"},{default:(0,r.k6)(()=>[...a[18]||(a[18]=[(0,r.eW)("Texas Instruments LAUNCHXL-CC1352P-2/CC26X2R1 only: press the reset button on the device",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#cc2531-coordinators-only-press-the-reset-button-on-the-device"},{default:(0,r.k6)(()=>[...a[19]||(a[19]=[(0,r.eW)("CC2531 coordinators only: press the reset button on the device",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#texas-instruments-launchxl-cc26x2r1-coordinator-only-verify-that-you-have-the-correct-revision"},{default:(0,r.k6)(()=>[...a[20]||(a[20]=[(0,r.eW)("Texas Instruments LAUNCHXL-CC26X2R1 coordinator only: verify that you have the correct revision",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#emberznet-coordinators-only"},{default:(0,r.k6)(()=>[...a[21]||(a[21]=[(0,r.eW)("EmberZNet coordinators only",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#multiple-cheap-usb-uart"},{default:(0,r.k6)(()=>[...a[22]||(a[22]=[(0,r.eW)("Multiple cheap USB-UART",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#mqtt-v5-disconnecting"},{default:(0,r.k6)(()=>[...a[23]||(a[23]=[(0,r.eW)("MQTT v5 disconnecting",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#error-startup-failed-configuration-adapter-mismatch-see-logs-above-for-more-information"},{default:(0,r.k6)(()=>[...a[24]||(a[24]=[(0,r.eW)("Error: startup failed - configuration-adapter mismatch - see logs above for more information",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#zigbee-adapters-over-the-network-use-robust-and-reliable-network-adapters-on-zigbee2mqtt-server"},{default:(0,r.k6)(()=>[...a[25]||(a[25]=[(0,r.eW)("Zigbee adapters over the network: use robust and reliable network adapters on Zigbee2MQTT server",-1)])]),_:1})]),(0,r.Lk)("li",null,[(0,r.bF)(t,{to:"#error-regular-crashes-with-timeout-errors-or-failure-to-start-after-the-serial-port-is-opened"},{default:(0,r.k6)(()=>[...a[26]||(a[26]=[(0,r.eW)("Error: regular crashes with timeout errors or failure to start after the serial port is opened",-1)])]),_:1})])])]),a[60]||(a[60]=(0,r.Lk)("h2",{id:"error-usb-adapter-discovery-error-no-valid-usb-adapter-found-specify-valid-adapter-and-port-in-your-configuration",tabindex:"-1"},[(0,r.Lk)("a",{class:"header-anchor",href:"#error-usb-adapter-discovery-error-no-valid-usb-adapter-found-specify-valid-adapter-and-port-in-your-configuration"},[(0,r.Lk)("span",null,[(0,r.eW)("Error: "),(0,r.Lk)("code",null,"USB adapter discovery error (No valid USB adapter found). Specify valid 'adapter' and 'port' in your configuration.")])])],-1)),(0,r.Lk)("p",null,[a[28]||(a[28]=(0,r.eW)("Configure the ",-1)),a[29]||(a[29]=(0,r.Lk)("code",null,"serial",-1)),a[30]||(a[30]=(0,r.eW)(" section as described ",-1)),(0,r.bF)(i,{to:"/guide/configuration/adapter-settings.html"},{default:(0,r.k6)(()=>[...a[27]||(a[27]=[(0,r.eW)("here",-1)])]),_:1}),a[31]||(a[31]=(0,r.eW)(".",-1))]),a[61]||(a[61]=(0,r.Lk)("h2",{id:"error-srsp-sys-ping-after-6000ms-for-zstack-or-host-fatal-error-for-emberznet",tabindex:"-1"},[(0,r.Lk)("a",{class:"header-anchor",href:"#error-srsp-sys-ping-after-6000ms-for-zstack-or-host-fatal-error-for-emberznet"},[(0,r.Lk)("span",null,[(0,r.eW)("Error: "),(0,r.Lk)("code",null,"SRSP - SYS - ping after 6000ms"),(0,r.eW)(" for zStack or "),(0,r.Lk)("code",null,"HOST_FATAL_ERROR"),(0,r.eW)(" for EmberZNet")])])],-1)),a[62]||(a[62]=(0,r.Lk)("p",null,"Common reasons for this error:",-1)),(0,r.Lk)("ol",null,[(0,r.Lk)("li",null,[a[33]||(a[33]=(0,r.eW)("The port of your serial adapter changed. Check ",-1)),(0,r.bF)(i,{to:"/guide/configuration/adapter-settings.html"},{default:(0,r.k6)(()=>[...a[32]||(a[32]=[(0,r.eW)("this",-1)])]),_:1}),a[34]||(a[34]=(0,r.eW)(" to find out the port of your adapter.",-1))]),(0,r.Lk)("li",null,[a[36]||(a[36]=(0,r.eW)("If you are using a CC2530 or CC2531; it is a common issue for this adapter to crash (due to its outdated hardware). Reflashing the firmware should fix the problem. If it happens often consider flashing the ",-1)),a[37]||(a[37]=(0,r.Lk)("a",{href:"https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing",target:"_blank",rel:"noopener noreferrer"},"source routing firmware",-1)),a[38]||(a[38]=(0,r.eW)(" or upgrade to a ",-1)),(0,r.bF)(i,{to:"/guide/adapters/"},{default:(0,r.k6)(()=>[...a[35]||(a[35]=[(0,r.eW)("more powerful adapter",-1)])]),_:1}),a[39]||(a[39]=(0,r.eW)(".",-1))]),(0,r.Lk)("li",null,[a[41]||(a[41]=(0,r.eW)("Your adapter requires additional configuration parameters. Check ",-1)),(0,r.bF)(i,{to:"/guide/adapters/"},{default:(0,r.k6)(()=>[...a[40]||(a[40]=[(0,r.eW)("supported Adapters",-1)])]),_:1}),a[42]||(a[42]=(0,r.eW)(" section to find out if your adapter requires extra parameters (eg. ConBee II / RaspBee II).",-1))]),a[43]||(a[43]=(0,r.Lk)("li",null,'Home Assistant\'s "Zigbee Home Automation" (ZHA) integration is enabled. Try to disable the ZHA integration and restart the Zigbee2MQTT add-on.',-1)),a[44]||(a[44]=(0,r.Lk)("li",null,"Your hardware adapter is flashed with the router firmware and not with the coordinator firmware.",-1)),a[45]||(a[45]=(0,r.Lk)("li",null,"Your network Zigbee adapter is not accessible over the LAN network.",-1)),a[46]||(a[46]=(0,r.Lk)("li",null,[(0,r.eW)("Another software on your machine (including Home Assistant integration) is interfering with USB devices (example: "),(0,r.Lk)("a",{href:"https://www.home-assistant.io/integrations/edl21",target:"_blank",rel:"noopener noreferrer"},"HA EDL21 integration"),(0,r.eW)(" trying to find a USB device).")],-1))]),a[63]||(a[63]=(0,r.Fv)('<h2 id="verify-that-you-put-the-correct-port-in-configuration-yaml" tabindex="-1"><a class="header-anchor" href="#verify-that-you-put-the-correct-port-in-configuration-yaml"><span>Verify that you put the correct port in configuration.yaml</span></a></h2><p>Execute the following command to find out the correct path:</p><div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre><code class="language-bash"><span class="line">pi@raspberry:/ $ <span class="token function">ls</span> <span class="token parameter variable">-l</span> /dev/serial/by-id</span>\n<span class="line">total <span class="token number">0</span></span>\n<span class="line">lrwxrwxrwx. <span class="token number">1</span> root root <span class="token number">13</span> Oct <span class="token number">19</span> <span class="token number">19</span>:26 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00 -<span class="token operator">&gt;</span> <span class="token punctuation">..</span>/<span class="token punctuation">..</span>/ttyACM0</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In this example the correct <code>port</code> would be <code>/dev/ttyACM0</code>.</p><h3 id="which-port-should-i-use-for-texas-instruments-launchxl-cc26x2r1-cc1352p-2-dev-ttyacm0-or-dev-ttyacm1" tabindex="-1"><a class="header-anchor" href="#which-port-should-i-use-for-texas-instruments-launchxl-cc26x2r1-cc1352p-2-dev-ttyacm0-or-dev-ttyacm1"><span>Which port should I use for Texas Instruments LAUNCHXL-CC26X2R1/CC1352P-2, /dev/ttyACM0 or /dev/ttyACM1?</span></a></h3><p>The Texas Instruments launchpad has a build in debugger. This debugger also registers a port next to the device data port. Of course this is not necessarily number 0 and 1. But normally the lowest number is the device data port and the other the debugger.</p><p>To find the correct port, execute:</p><div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre><code class="language-bash"><span class="line">pi@raspberry:/ $ <span class="token function">ls</span> <span class="token parameter variable">-l</span> /dev/serial/by-id</span>\n<span class="line">total <span class="token number">0</span></span>\n<span class="line">lrwxrwxrwx <span class="token number">1</span> root root <span class="token number">13</span> Jan  <span class="token number">6</span> <span class="token number">19</span>:07 usb-Texas_Instruments_XDS110__03.00.00.05__Embed_with_CMSIS-DAP_L1100BTD-if00 -<span class="token operator">&gt;</span> <span class="token punctuation">..</span>/<span class="token punctuation">..</span>/ttyACM0</span>\n<span class="line">lrwxrwxrwx <span class="token number">1</span> root root <span class="token number">13</span> Jan  <span class="token number">6</span> <span class="token number">19</span>:07 usb-Texas_Instruments_XDS110__03.00.00.05__Embed_with_CMSIS-DAP_L1100BTD-if03 -<span class="token operator">&gt;</span> <span class="token punctuation">..</span>/<span class="token punctuation">..</span>/ttyACM1</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The device with id ending with <em>if00</em> is for device data. Use this port in your configuration.</p><h2 id="verify-that-the-user-you-run-zigbee2mqtt-as-has-write-access-to-the-port" tabindex="-1"><a class="header-anchor" href="#verify-that-the-user-you-run-zigbee2mqtt-as-has-write-access-to-the-port"><span>Verify that the user you run Zigbee2MQTT as has write access to the port</span></a></h2><p>This can be tested by executing: <code>test -w [PORT] &amp;&amp; echo success || echo failure</code> ( e.g. <code>test -w /dev/ttyACM0 &amp;&amp; echo success || echo failure</code>).</p><p>If it outputs <code>failure</code> it could mean your user does not have access to the port. To test assign write access by executing: <code>sudo chown [USER] [PORT]</code> (e.g. <code>sudo chown pi /dev/ttyACM0</code>).</p><p>if it outputs <code>failure</code>, then you need to permanently give your user permission to the device.</p><h3 id="method-1-give-your-user-permissions-on-every-reboot" tabindex="-1"><a class="header-anchor" href="#method-1-give-your-user-permissions-on-every-reboot"><span>Method 1: Give your user permissions on every reboot.</span></a></h3><p>You can create a &#39;udev&#39; rule to give your user permissions after every reboot:</p><ol><li><p><code>udevadm info -a -n /dev/ttyACM0 | grep &#39;serial&#39;</code> get the serial to your device <code>YOURSERIAL</code></p></li><li><p>Create the rule file with: <code>sudo nano /etc/udev/rules.d/99-usb-serial.rules</code></p></li><li><p>add this line: <code>SUBSYSTEM==&quot;tty&quot;, ATTRS{idVendor}==&quot;0451&quot;, ATTRS{idProduct}==&quot;16a8&quot;, ATTRS{serial}==&quot;YOURSERIAL&quot;, SYMLINK=&quot;ttyUSB.CC2531-01&quot;, OWNER=&quot;pi&quot;</code></p></li><li><p>modify your Zigbee2MQTT config to adjust new SYMLINK name: <code>nano /opt/zigbee2mqtt/data/configuration.yaml</code></p></li></ol><p><code>… serial: port: /dev/ttyUSB.CC2531-01 …</code></p><p>After reboot your device will have the right permissions and always the same name.</p><h3 id="method-2-add-your-user-to-specific-groups" tabindex="-1"><a class="header-anchor" href="#method-2-add-your-user-to-specific-groups"><span>Method 2: Add your user to specific groups</span></a></h3><p>As mentioned on https://github.com/esp8266/source-code-examples/issues/26 , depending on your linux installation, various groups could have ownership of the device.</p><p>Add your user to the <code>uucp </code> , <code>tty </code> , <code>dialout </code> groups:</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">sudo usermod -a -G uucp $USER</span>\n<span class="line">sudo usermod -a -G tty $USER</span>\n<span class="line">sudo usermod -a -G dialout $USER</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Reboot your device and now your user should have access to the device.</p><h2 id="error-coordinator-failed-to-start-probably-the-panid-is-already-in-use-try-a-different-panid-or-channel" tabindex="-1"><a class="header-anchor" href="#error-coordinator-failed-to-start-probably-the-panid-is-already-in-use-try-a-different-panid-or-channel"><span>Error: <code>Coordinator failed to start, probably the panID is already in use, try a different panID or channel</code></span></a></h2>',24)),(0,r.Lk)("ul",null,[(0,r.Lk)("li",null,[a[48]||(a[48]=(0,r.eW)("If you still get this error after increasing the panID (as explained ",-1)),(0,r.bF)(i,{to:"/guide/configuration/zigbee-network.html#network-config"},{default:(0,r.k6)(()=>[...a[47]||(a[47]=[(0,r.eW)("here",-1)])]),_:1}),a[49]||(a[49]=(0,r.eW)(") and you are using a Raspberry Pi with other USB devices attached (e.g. SSD) try connecting the SSD or adapter through a powered USB hub.",-1))]),a[50]||(a[50]=(0,r.Lk)("li",null,[(0,r.eW)("In case you are getting this after first starting successfully and pairing a device it might be that the firmware has been flashed incorrectly. Try flashing the stick on a different computer ("),(0,r.Lk)("a",{href:"https://github.com/Koenkk/zigbee2mqtt/issues/6302",target:"_blank",rel:"noopener noreferrer"},"detailed info"),(0,r.eW)("). This issue mainly occurs in combination with a Slaesh's CC2652RB stick.")],-1)),a[51]||(a[51]=(0,r.Lk)("li",null,"If you had your Zigbee network before and such an error appears with the new Zigbee adapter, try to switch off the Zigbee routers that were connected to your previous Zigbee network and restart Zigbee2MQTT.",-1))]),a[64]||(a[64]=(0,r.Fv)('<h2 id="error-resource-temporarily-unavailable-cannot-lock-port" tabindex="-1"><a class="header-anchor" href="#error-resource-temporarily-unavailable-cannot-lock-port"><span>Error: <code>Resource temporarily unavailable Cannot lock port</code></span></a></h2><p>This error occurs when another program is already using (and thus locking) the adapter. You can find out which via the following command: <code>ls -l /proc/[0-9]/fd/ |grep /dev/ttyACM0</code> (replace <code>/dev/ttyACM0</code> with your adapter port).</p><h2 id="raspberry-pi-users" tabindex="-1"><a class="header-anchor" href="#raspberry-pi-users"><span>Raspberry Pi users</span></a></h2><h2 id="raspberry-pi-os" tabindex="-1"><a class="header-anchor" href="#raspberry-pi-os"><span>Raspberry Pi OS</span></a></h2><p>Make sure that you are using at least Raspberry Pi OS 11. To figure out which version you are running execute:</p><div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre><code class="language-bash"><span class="line"><span class="token function">cat</span> /etc/issue.net</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div></div></div><h2 id="use-a-good-power-supply" tabindex="-1"><a class="header-anchor" href="#use-a-good-power-supply"><span>Use a good power supply</span></a></h2><p>A bad power supply can make your system and its USB devices unstable. Make sure to use a good power supply.</p><p>In case you see message like below when running <code>dmesg -w</code> you are using a bad power supply.</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">[44870.355590] Under-voltage detected! (0x00050005)</span>\n<span class="line">[44874.515618] Voltage normalised (0x00000000)</span>\n<span class="line">[44880.755718] Under-voltage detected! (0x00050005)</span>\n<span class="line">[44889.075627] Voltage normalised (0x00000000)</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Also try connecting the adapter via a powered USB hub (especially if you have an SSD connected to the Pi).</p><h2 id="make-sure-the-extension-cable-works" tabindex="-1"><a class="header-anchor" href="#make-sure-the-extension-cable-works"><span>Make sure the extension cable works</span></a></h2><p>A bad extension cable can lead to connection issues between the system and the adapter. Symptoms of this are disconnection messages in the <code>dmesg -w</code> log like below.</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">[44929.156957] usb 1-1.5: USB disconnect, device number 119</span>\n<span class="line">[44929.455555] usb 1-1.5: new full-speed USB device number 120 using dwc_otg</span>\n<span class="line">[44929.604582] usb 1-1.5: New USB device found, idVendor=0451, idProduct=16a8, bcdDevice= 0.09</span>\n<span class="line">[44929.604596] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3</span>\n<span class="line">[44929.604606] usb 1-1.5: Product: TI CC2531 USB CDC</span>\n<span class="line">[44929.604615] usb 1-1.5: Manufacturer: Texas Instruments</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="for-openhab-users-disable-zwave-binding" tabindex="-1"><a class="header-anchor" href="#for-openhab-users-disable-zwave-binding"><span>For Openhab users: disable zwave binding</span></a></h2><p>The Openhab zwave binding interferes with Zigbee2MQTT, click <a href="https://community.openhab.org/t/apparently-the-zwave-binding-blocks-the-dev-ttyusb0-port-in-combination-with-a-cc2652rb-zigbee2mqtt-dongle/103245" target="_blank" rel="noopener noreferrer">here</a> for more information.</p><h2 id="in-case-of-a-cc2530-or-cc2531-adapter-verify-that-don-t-have-a-cc2540" tabindex="-1"><a class="header-anchor" href="#in-case-of-a-cc2530-or-cc2531-adapter-verify-that-don-t-have-a-cc2540"><span>In case of a CC2530 or CC2531 adapter, verify that don&#39;t have a CC2540</span></a></h2><p>The CC2540 can be confused easily with the CC2531 as it looks (almost) exactly the same. However, this device does not support zigbee but bluetooth. This can be verified by looking at the chip.</p><h2 id="modemmanager-is-installed" tabindex="-1"><a class="header-anchor" href="#modemmanager-is-installed"><span><a href="https://www.freedesktop.org/wiki/Software/ModemManager/" target="_blank" rel="noopener noreferrer">ModemManager</a> is installed</span></a></h2><p>ModemManager, which is default installed on e.g. Ubuntu, is known to cause problems. It can easily be fixed by removing ModemManager through <code>sudo apt-get purge modemmanager</code>.</p><h2 id="make-sure-your-computer-has-enough-resources-available" tabindex="-1"><a class="header-anchor" href="#make-sure-your-computer-has-enough-resources-available"><span>Make sure your computer has enough resources available</span></a></h2><p>Serial communication may experience instability if your computer is low on resources. If your CPU and memory consistently operate at full capacity, it might suggest a shortage of resources. For instance, using the Zigee2MQTT addon in Home Assistant on a Raspberry Pi 3 can lead to resource exhaustion.</p><h2 id="hciuart-is-running" tabindex="-1"><a class="header-anchor" href="#hciuart-is-running"><span>hciuart is running</span></a></h2><p>hciuart can be disabled by executing: <code>sudo systemctl disable hciuart</code>.</p><h2 id="texas-instruments-launchxl-cc1352p-2-cc26x2r1-only-press-the-reset-button-on-the-device" tabindex="-1"><a class="header-anchor" href="#texas-instruments-launchxl-cc1352p-2-cc26x2r1-only-press-the-reset-button-on-the-device"><span>Texas Instruments LAUNCHXL-CC1352P-2/CC26X2R1 only: press the reset button on the device</span></a></h2><p>If Zigbee2MQTT fails to start with a Texas Instruments LAUNCHXL-CC1352P-2/CC26X2R1 with <code>Error: SRSP - SYS - version after 6000ms</code>, you most probably have connected your device to a system that requires pressing the reset button (the one next to the USB connector) momentarily/shortly after connecting the USB cable. This issue has primarily been observed on x86 architectures only ( e.g., Intel NUC, HPE Microserver, i7 laptop), see also <a href="https://github.com/Koenkk/zigbee2mqtt/issues/2162" target="_blank" rel="noopener noreferrer">#2162</a>. The procedure has to be repeated every time the adapter is re-connected and it&#39;s not clear yet, whether this can be fixed at all. It does not seem to occur on ARM based boards (Raspberry Pi, ODROID XU4).</p><p>Something that can also solve the issue is to replug the USB cable.</p><h2 id="cc2531-coordinators-only-press-the-reset-button-on-the-device" tabindex="-1"><a class="header-anchor" href="#cc2531-coordinators-only-press-the-reset-button-on-the-device"><span>CC2531 coordinators only: press the reset button on the device</span></a></h2><p>When you plug the CC2531 in your computer, the green LED should go on. By pressing the reset button on the CC2531 the green LED should go off. The CC2531 has 2 buttons on it, the reset button is the one which is closest to the USB port. Now try starting Zigbee2MQTT again.</p><h2 id="texas-instruments-launchxl-cc26x2r1-coordinator-only-verify-that-you-have-the-correct-revision" tabindex="-1"><a class="header-anchor" href="#texas-instruments-launchxl-cc26x2r1-coordinator-only-verify-that-you-have-the-correct-revision"><span>Texas Instruments LAUNCHXL-CC26X2R1 coordinator only: verify that you have the correct revision</span></a></h2><p>The revision of your board can be seen in UniFlash by clicking <em>more info</em> in the top, now press <em>Read device info</em>.</p><p>The correct revision is: <strong>E</strong> like shown below.</p><p><img src="'+s+'" alt="cc26xr1_revision"></p><p>All earlier version are not supported (these are development boards). Return this board to the seller immediately.</p><h2 id="emberznet-coordinators-only" tabindex="-1"><a class="header-anchor" href="#emberznet-coordinators-only"><span>EmberZNet coordinators only</span></a></h2>',35)),(0,r.Lk)("p",null,[a[53]||(a[53]=(0,r.eW)("See ",-1)),(0,r.bF)(i,{to:"/guide/adapters/emberznet.html#error-level"},{default:(0,r.k6)(()=>[...a[52]||(a[52]=[(0,r.eW)("EmberZNet errors",-1)])]),_:1}),a[54]||(a[54]=(0,r.eW)(".",-1))]),a[65]||(a[65]=(0,r.Lk)("h2",{id:"multiple-cheap-usb-uart",tabindex:"-1"},[(0,r.Lk)("a",{class:"header-anchor",href:"#multiple-cheap-usb-uart"},[(0,r.Lk)("span",null,"Multiple cheap USB-UART")])],-1)),a[66]||(a[66]=(0,r.Lk)("p",null,"If you have multiple devices connected that are running cheap USB-UART converters (CH341) they may be indistinguishable to your system, since they all possibly have the same idProduct, SerialNumber etc. so they will share the same /dev/serial/by-id. The easiest solution is to change one of your devices to something with a different uart-usb converter. The second solution would be swapping the whole converter or adding external EEPROM memory to a chip that does not have one (like CH341) so you would be able to add a serial number.",-1)),a[67]||(a[67]=(0,r.Lk)("h2",{id:"mqtt-v5-disconnecting",tabindex:"-1"},[(0,r.Lk)("a",{class:"header-anchor",href:"#mqtt-v5-disconnecting"},[(0,r.Lk)("span",null,"MQTT v5 disconnecting")])],-1)),a[68]||(a[68]=(0,r.Lk)("p",null,'If you use an MQTT broker with version 5 of the MQTT specification, you may get disconnects when something is misbehaving. This can happen, for example, when "maximum packet size" is exceeded (large networks).',-1)),(0,r.Lk)("p",null,[a[56]||(a[56]=(0,r.eW)("To remedy that, configure your broker accordingly, and check if Zigbee2MQTT has a corresponding setting to adjust too. See ",-1)),(0,r.bF)(i,{to:"/guide/configuration/mqtt.html#server-connection"},{default:(0,r.k6)(()=>[...a[55]||(a[55]=[(0,r.eW)("MQTT configuration",-1)])]),_:1}),a[57]||(a[57]=(0,r.eW)(".",-1))]),a[69]||(a[69]=(0,r.Fv)('<h2 id="error-startup-failed-configuration-adapter-mismatch-see-logs-above-for-more-information" tabindex="-1"><a class="header-anchor" href="#error-startup-failed-configuration-adapter-mismatch-see-logs-above-for-more-information"><span>Error: <code>startup failed - configuration-adapter mismatch - see logs above for more information</code></span></a></h2><p>This happens when you edit one or more of the <code>pan_id</code>, <code>network_key</code> or <code>ext_pan_id</code> values in <code>configuration.yml</code>. If your intent was to do this, the easiest way to resolve this error is to remove the <code>data/coordinator-backup.json</code> file and restart again. Note that this will reset your network and <strong>all devices will need to be re-paired!</strong>. Alternatively, you can revert back to the previous value(s). In that case, look a few lines before the error in the log, you&#39;ll find something like this:</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">[2024-12-14 20:25:39] error: \tzh:adapter:zstack:manager: Configuration is not consistent with adapter state/backup!</span>\n<span class="line">[2024-12-14 20:25:39] error: \tzh:adapter:zstack:manager: - PAN ID: configured=****, adapter=****</span>\n<span class="line">[2024-12-14 20:25:39] error: \tzh:adapter:zstack:manager: - Extended PAN ID: configured=****, adapter=****</span>\n<span class="line">[2024-12-14 20:25:39] error: \tzh:adapter:zstack:manager: - Network Key: configured=****, adapter=****</span>\n<span class="line">[2024-12-14 20:25:39] error: \tzh:adapter:zstack:manager: - Channel List: configured=**, adapter=**</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>(In this example the actual values are replaced with <code>*</code>s) You can used the values that are listed for the adapter and put them back in the configuration file. Note that you can&#39;t just paste them back: in the logs the keys are printed as hexadecimal strings, but in the config file, <code>ext_pan_id</code> and <code>ext_pan_id</code> should be entered as arrays. Suppose your network key shows as <code>39af4d83h2dcb389</code> in the logs, then you should put the following in your config file:</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">ext_pan_id: [0x39,0xaf,0x4d,0x83,0xh2,0xdc,0xb3,0x89]</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div></div></div><h2 id="zigbee-adapters-over-the-network-use-robust-and-reliable-network-adapters-on-zigbee2mqtt-server" tabindex="-1"><a class="header-anchor" href="#zigbee-adapters-over-the-network-use-robust-and-reliable-network-adapters-on-zigbee2mqtt-server"><span>Zigbee adapters over the network: use robust and reliable network adapters on Zigbee2MQTT server</span></a></h2><p>If you have a WiFi or ethernet-connected Zigbee adapter, Zigbee2MQTT is communicating with the Zigbee adapter over the LAN through serial-over-IP protocol.</p><p>The use of USB-WiFi or USB-ethernet adapters on the Zigbee2MQTT server is discouraged because despite the apparent equivalence to the onboard adapters in terms of specifications, they are designed in small enclosures, often not well ventilated and tend to overheat.<br> These adapters are known to stall or stop working in case of high loads or overheating, causing errors like:</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">[2024-06-24 03:37:22] error: zh:ember:uart:ash: Received ERROR from NCP while connecting, with code=ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT.</span>\n<span class="line">[2024-06-24 03:37:22] error: zh:ember:uart:ash: ASH disconnected | NCP status: ASH_NCP_FATAL_ERROR</span>\n<span class="line">[2024-06-24 03:37:22] error: zh:ember:uart:ash: Error while parsing received frame, status=ASH_NCP_FATAL_ERROR.</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>where a timeout occurred on the serial-over-IP protocol, or:</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">[2024-06-24 03:37:24] warning: zh:ember:uart:ash: Frame(s) in progress cancelled in [1ac1020b0a527e]</span>\n<span class="line">[2024-06-24 03:37:24] error: zh:ember:uart:ash: Received unexpected reset from NCP, with reason=RESET_SOFTWARE.</span>\n<span class="line">[2024-06-24 03:37:24] error: zh:ember:uart:ash: ASH disconnected: ASH_ERROR_NCP_RESET | NCP status: ASH_NCP_FATAL_ERROR</span>\n<span class="line">[2024-06-24 03:37:24] error: zh:ember:uart:ash: Error while parsing received frame, status=HOST_FATAL_ERROR.</span>\n<span class="line">[2024-06-24 03:37:24] error: zh:ember: !!! NCP FATAL ERROR reason=HOST_FATAL_ERROR. ATTEMPTING RESET... !!!</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>which shows a communication out of sync between host and NCP but also, and this is a clear hint of network problems:</p><div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre><code class="language-text"><span class="line">[2024-06-24 03:38:05] error: z2m:mqtt: Not connected to MQTT server!</span>\n<span class="line">[2024-06-24 03:38:05] error: z2m:mqtt: Cannot send message: topic: &#39;zigbee2mqtt/bridge/state&#39;, payload: &#39;{&quot;state&quot;:&quot;offline&quot;}</span>\n<span class="line">[2024-06-24 03:38:05] info: z2m:mqtt: Disconnecting from MQTT server</span>\n<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>where Zigbee2MQTT could not connect to the MQTT server over the LAN.</p><p>The best setup for this situation is to use the ethernet port embedded into the Zigbee2MQTT server motherboard which guarantees reliability of communications in all load conditions.<br> As a second choice you can use the onboard WiFi adapter which should as well be designed for reliability, but also consider the stability of your WiFi network.<br> If all the onboard adapters are in use and you need to add another network adapter, the best choice is to install an internal network card on the PCIe bus, with proper cooling design.</p><h2 id="error-regular-crashes-with-timeout-errors-or-failure-to-start-after-the-serial-port-is-opened" tabindex="-1"><a class="header-anchor" href="#error-regular-crashes-with-timeout-errors-or-failure-to-start-after-the-serial-port-is-opened"><span>Error: regular crashes with timeout errors or failure to start after the serial port is opened</span></a></h2><p>These errors may occur when the serial communication between the Zigbee dongle and Zigbee2MQTT unexpectedly stops working.</p><p>Possible reasons that may cause this error:</p><ol><li><p>The hardware connection between the host computer and the Zigbee dongle is unreliable. In the following example a cheap USB cable causing unreliable connection is compared with a good USB cable: <img src="'+n+'" alt="good-vs-bad-usb-cable"> With such cheap cable it is enough to touch the cable to cause USB disconnections.</p></li><li><p>Zigbee2MQTT is running in a Virtual Machine and the USB passthrough between the host and the VM is unreliable. This can be caused by the virtualization environment, the USB hardware or a combination of both. If these error appear, we can do something to reduce the complexity of the setup, improve stability and help investigating the usb connection with the host. Instead of passing through to the VM the full USB device we passthrough the serial device. The VM configuration changes from host-(USB passthrough)-&gt;VM-&gt;USB-serial-&gt;serial(for Zigbee2MQTT configuration) to host-(serial passthrough)-&gt;VM-&gt;serial(for Zigbee2MQTT configuration)</p></li></ol><p>As an example, this is the procedure to passthrough the serial device to a Proxmox Home Assistant OS installation:</p><ul><li>Add a serial0 (or serial1 or 2 or 3) to the proxmox VM hardware<br> By default the serial port is a socket in the Proxmox hardware VM config (&quot;serial0: socket&quot;) so we have to change this parameter in the VM configuration file /etc/pve/quemu-server/{VMID}.conf to point to the real serial device, for example: &quot;serial0: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240122184528-if00&quot;</li><li>Free up the ttyS0 serial port from getty in Home Assistant OS<br> In the VM this serial port passed through is recognized as ttyS0, but the Home Assistant OS systemd by default is spawning an agetty on /dev/ttyS0, in factin the file /mnt/boot/cmdline.txt kernel commandline parameters the ttyS0 is set as console (content is &quot;console=ttyS0 console=tty0&quot;). We have to change this cmdline.txt file in the VM so that systemd leaves ttyS0 alone without spawning agetty, therefore we remove the ttyS0 part and the cmdline.txt becomes &quot;console=tty0&quot;.</li></ul><p>Now Zigbee2MQTT is able to reach the dongle through /dev/ttyS0 which is a &quot;real&quot; serial port inside the VM. Any issue with the USB device is logged by the host kernel and can be easily spotted with dmesg in this way we isolate them from the issues on the serial device.</p>',22))])}]]),d=JSON.parse('{"path":"/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html","title":"Zigbee2MQTT fails to start/crashes runtime","lang":"en-US","frontmatter":{"pageClass":"content-page","sidebarDepth":0},"git":{"updatedTime":1762029806000,"contributors":[{"name":"Koen Kanters","username":"","email":"koenkanters94@gmail.com","commits":1}],"changelog":[{"hash":"65fac821d7d53a7e50cd38541621bbb5ac5d9dd0","time":1762029806000,"email":"koenkanters94@gmail.com","author":"Koen Kanters","message":"Update zhc to 25.59.0"}]},"filePathRelative":"guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.md"}')}}]);